### ISSUE TITLE
家族の収支の年に数回 ②を入力したときにキャッシュフロー表に反映されない

### ISSUE THREAD

**Issue by albatrosary** [ashiras/financial-plan#10]
家族の収支（ncome-confirmation） の「年に数回 ②」を入力したときにキャッシュフロー表に反映されない

**Comment by albatrosary** [comment]
キャッシュフロー表の支出が月費用が表示されているので年間費用にする

**Comment by knh8205** [comment]
修正完了と思われるためClose
